#!/bin/bash
set -e
CMD_DIR="$HOME/.claude/commands/flow"
mkdir -p "$CMD_DIR"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
echo "$SCRIPT_DIR" > "$CMD_DIR/.source"
cp "$SCRIPT_DIR"/skills/flow-status.md "$CMD_DIR/status.md"
cp "$SCRIPT_DIR"/skills/flow-done.md "$CMD_DIR/done.md"
cp "$SCRIPT_DIR"/skills/flow-init.md "$CMD_DIR/init.md"
cp "$SCRIPT_DIR"/skills/flow-spec.md "$CMD_DIR/spec.md"
cp "$SCRIPT_DIR"/skills/flow-go.md "$CMD_DIR/go.md"
cp "$SCRIPT_DIR"/skills/flow-intro.md "$CMD_DIR/intro.md"
cp "$SCRIPT_DIR"/skills/flow-task.md "$CMD_DIR/task.md"
cp "$SCRIPT_DIR"/skills/flow-update.md "$CMD_DIR/update.md"
echo ""
echo "Flow plugin installed successfully!"
echo "Commands available: /flow:intro, /flow:init, /flow:spec, /flow:go, /flow:done, /flow:status, /flow:task, /flow:update"
echo ""
echo "Get started: run /flow:intro in any Claude Code session for a walkthrough"
