#!/bin/bash
set -e
CMD_DIR="$HOME/.claude/commands/flow"
mkdir -p "$CMD_DIR"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cp "$SCRIPT_DIR"/skills/flow-status.md "$CMD_DIR/status.md"
cp "$SCRIPT_DIR"/skills/flow-done.md "$CMD_DIR/done.md"
cp "$SCRIPT_DIR"/skills/flow-init.md "$CMD_DIR/init.md"
cp "$SCRIPT_DIR"/skills/flow-spec.md "$CMD_DIR/spec.md"
cp "$SCRIPT_DIR"/skills/flow-go.md "$CMD_DIR/go.md"
echo ""
echo "Flow plugin installed successfully!"
echo "Commands available: /flow:init, /flow:spec, /flow:go, /flow:done, /flow:status"
echo ""
echo "Get started: open any project and run /flow:init"
